# Only Category 2: Source node fan-out & activity

_include_yml: velox_edge_engineered

edge_engineering:
  category_1_pair: False
  category_2_source: True
  category_3_type: False
  category_4_pair_type: False
  category_5_source_type: False
  category_6_global: False
  category_7_burst: False
